import traceback
from abc import ABC, abstractmethod
from collections.abc import Callable
from time import time
from typing import Any, Generic

from qcdata import (
    CalcType,
    Data,
    DataType,
    FileInput,
    InputType,
    ProgramInput,
    ProgramOutput,
)
from qcdata.helper_types import StrOrPath

from qccompute.exceptions import (
    AdapterInputError,
    QCComputeBaseError,
)

from .utils import construct_execution, empty_results, tmpdir

__all__ = ["BaseAdapter", "registry"]

# Registry for all Adaptors.
# NOTE: Registry stores class objects, not instances.
# Use registry[program]() to instantiate an adaptor
# Or use the higher level qccompute.utils.get_adapter() function.
registry = {}


class BaseAdapter(ABC, Generic[InputType, DataType]):
    """Base class for all adapters."""

    # Whether to this program reads or writes files to disk.
    # If True, the adapter will write all files from input_data to a disk before executing
    # the program. If False, the adapter must handle input files itself in some other
    # way. Generally this should be True for most adapters unless the program can
    # handle input files directly from memory, stdin, or some other mechanism that is
    # more efficient than writing to disk.
    uses_files = True
    program: str  # All subclasses must define this attribute.

    @property
    def producer_program(self) -> str:
        return getattr(self, "external_program", self.program)

    def program_version(self, stdout: str | None) -> str | None:
        """Return program version. Adapters should override this method.

        Args:
            stdout: The stdout from the program. Because running "program --version"
                can be extremely slow for some programs, the stdout from the program
                is passed in here so that the version can be extracted from it if
                possible. If the version cannot be extracted from the stdout, then
                this function should return the program version in some other way.
        """
        return None

    @abstractmethod
    def validate_input(self, input_data: InputType) -> None:
        """Validate input_data to ensure compatibility with adapter.
        Adapters should override this method.
        """
        raise NotImplementedError

    @abstractmethod
    def compute_data(
        self,
        input_data: InputType,
        update_func: Callable | None = None,
        update_interval: float | None = None,
        **kwargs,
    ) -> tuple[DataType, str]:
        """Subclasses should implement this method with custom compute logic."""
        raise NotImplementedError

    def compute(
        self,
        input_data: InputType,
        *,
        scratch_dir: StrOrPath | None = None,
        rm_scratch_dir: bool = True,
        collect_logs: bool = True,
        collect_files: bool = False,
        collect_wfn: bool = False,
        update_func: Callable | None = None,
        update_interval: float | None = None,
        print_logs: bool = False,
        raise_exc: bool = True,
        propagate_wfn: bool = False,
        **adapter_kwargs: Any,
    ) -> ProgramOutput[InputType, DataType]:
        """Compute the given input using the adapter's program.

        Args:
            input_data: A qcdata input object for a computation. E.g. A FileInput,
                ProgramInput.
            scratch_dir: The scratch directory for the program. If None, a new directory
                is created in the system default temporary directory. If rm_scratch_dir
                is True this directory will be deleted after the program finishes.
            rm_scratch_dir: Delete the scratch directory after the program exits.
            collect_logs: Whether to collect stdout/stderr from the program as output.
                Failed computations will always collect stdout/stderr.
            collect_files: Collect all files generated by the QC program as output.
            collect_wfn: Collect the wavefunction file(s) from the calculation.
                Not every program will support this. Use collect_files to collect
                all files including the wavefunction.
            update_func: A function to call as the program executes. The function must
                accept the in-process stdout/stderr output as a string for its first
                argument.
            update_interval: The minimum time in seconds between calls to the
                update_func.
            print_logs: Whether to print stdout/stderr to the terminal in real time as
                the program executes. Will be ignored if an update_func passed.
            raise_exc: If False, qccompute will return a ProgramOutput object when the QC
                program fails rather than raise an exception.
            propagate_wfn: For any adapter performing a sequential task, such
                as a geometry optimization, propagate the wavefunction from the previous
                step to the next step. This is useful for accelerating convergence by
                using a previously computed wavefunction as a starting guess. If an
                adapter does not support wavefunction propagation, an AdapterInputError
                will be raised.
            **adapter_kwargs: Additional keyword arguments to pass to the adapter or
                qcng.compute().

        Returns:
            A ProgramOutput object containing the results of the computation.

        Raises:
            AdapterNotFoundError: If the program is not supported (i.e., no Adapter
                is implemented for the program in qccompute or qcengine).
            ProgramNotFoundError: If the program executable is not found on the
                system at execution time. This likely means the program is not installed
                or not available on the $PATH.
            AdapterInputError: If the input is invalid for the adapter.
            ExternalProgramExecutionError: If the QC program fails during execution.
            QCEngineError: If QCEngine performs the computation raises an error.
        """
        # Print stdout to terminal in real time as program executes
        if print_logs and update_func is None:
            update_func, update_interval = (
                lambda _, stdout_new: print(stdout_new),
                0.1,
            )

        # cd to a temporary directory to run the program.
        with tmpdir(self.uses_files, scratch_dir, rm_scratch_dir) as final_scratch_dir:
            if self.uses_files:  # Write non structured input files to disk.
                input_data.save_files()

            # Define outputs
            prog_output_dict: dict[str, Any] = {}
            logs: str | None = None
            data: Data = empty_results(input_data, self.producer_program)
            exc: QCComputeBaseError | None = None
            program_version: str | None = None

            start = time()
            try:
                # Dispatch and the recorded request must agree.
                expected_program = getattr(self, "external_program", self.program)
                if input_data.program != expected_program:
                    raise AdapterInputError(
                        self.program,
                        f"Input requests {input_data.program!r}, not {expected_program!r}.",
                    )
                self.validate_input(input_data)

                # Execute the program. data will be FileData for FileInput
                data, logs = self.compute_data(
                    input_data,
                    update_func,
                    update_interval,
                    propagate_wfn=propagate_wfn,
                    **adapter_kwargs,
                )
                prog_output_dict["success"] = True

                # Optionally collect wavefunction file
                if collect_wfn and not collect_files:
                    data = type(data).model_validate(
                        {
                            **data.model_dump(),
                            "files": {**data.files, **self.collect_wfn()},
                        }
                    )

            except QCComputeBaseError as e:
                exc = e
                prog_output_dict["success"] = False
                # Any half-completed data
                data = e.data if e.data is not None else data
                logs = getattr(e, "logs", logs) or logs
                # For mypy because e.logs is not of a known type
                logs = str(logs) if logs is not None else None
                prog_output_dict["traceback"] = traceback.format_exc()

            wall_time = time() - start

            # Parsed producer metadata is authoritative. Fill an unknown version only
            # when the adapter can provide it; version lookup must not mask failure.
            if (
                data.provenance.program_version is None
                and data.provenance.program == self.producer_program
                and (logs or prog_output_dict["success"])
            ):
                try:
                    program_version = self.program_version(logs)
                except QCComputeBaseError:
                    program_version = None
                if program_version:
                    data = type(data).model_validate(
                        {
                            **data.model_dump(),
                            "provenance": {
                                **data.provenance.model_dump(),
                                "program_version": program_version,
                            },
                        }
                    )
            execution = construct_execution(final_scratch_dir, wall_time)

            # Always collect for failures; otherwise obey collect_logs
            logs = logs if not prog_output_dict["success"] or collect_logs else None

            # Construct ProgramOutput
            prog_output_dict.update(
                {
                    "input_data": input_data,
                    "logs": logs,
                    "results": data,
                    "execution": execution,
                }
            )
            prog_output = ProgramOutput(**prog_output_dict)

            # Collect files generated by the program
            if self.uses_files and (collect_files or type(input_data) is FileInput):
                prog_output.results.add_files(
                    final_scratch_dir,
                    recursive=True,
                    exclude=list(input_data.files.keys()),
                )

        # Append ProgramOutput to exception and raise if raise_exc=True
        # Helpful for BigChem and ChemCloud exception handling
        if raise_exc and exc:
            exc.prog_output = prog_output
            raise exc

        return prog_output

    def collect_wfn(self) -> dict[str, str | bytes]:
        """Collect the wavefunction file(s) from the scratch_dir.

        Returns:
            Dictionary of filenames and file data. E.g. {"c0": b"filedata"}

        """
        # Collect wavefunction file from the calc_dir
        raise AdapterInputError(
            program=self.program,
            message=f"Adapter for {self.program} does not support wavefunction collection.",
        )


class ProgramAdapter(BaseAdapter, Generic[InputType, DataType]):
    """Base adapter for all program adapters (all but FileAdaptor)."""

    requires_model = True

    supported_calctypes: list[
        CalcType
    ]  # All subclasses must specify supported calctypes

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        # Ensure that subclasses define the required class attributes
        if not getattr(cls, "program", None):
            raise NotImplementedError(
                f"Subclasses of {ProgramAdapter.__name__} must define a program "
                f"string. {cls.__name__} does not meet this requirement."
            )

        # Automatically register all subclasses
        registry[cls.program] = cls

        if not getattr(cls, "supported_calctypes", None):
            raise NotImplementedError(
                f"Subclasses of {ProgramAdapter.__name__} must define a nonempty "
                f"supported_calctypes list. {cls.__name__} does not meet this "
                "requirement."
            )

    @abstractmethod
    def program_version(self, stdout: str | None) -> str | None:
        """Get the version of the program.

        Args:
            stdout: The stdout from the program. Because running "program --version"
                can be extremely slow for some programs, the stdout from the program
                is passed in here so that the version can be extracted from it if
                possible. If the version cannot be extracted from the stdout, then
                this function should return the program version in some other way.
        """

    @abstractmethod
    def compute_data(
        self,
        input_data: InputType,
        update_func: Callable | None = None,
        update_interval: float | None = None,
        **kwargs,
    ) -> tuple[DataType, str]:
        """All ProgramAdapters must return a DataType."""
        raise NotImplementedError

    def validate_input(self, input_data: ProgramInput) -> None:
        """Validate the input object for compatibility with the adapter.

        Args:
            input_data: The input object to validate.

        Raises:
            AdapterInputError: If the input object's calctype is not supported.
        """
        if self.requires_model and input_data.model is None:
            raise AdapterInputError(
                self.program, "This program requires a scientific model."
            )
        if input_data.calctype not in self.supported_calctypes:
            raise AdapterInputError(
                program=self.program,
                message=(
                    f"The {self.program} adapter does not yet support "
                    f"'{input_data.calctype.value}' calculations. This adaptor can "
                    f"compute: {[ct.value for ct in self.supported_calctypes]}"
                ),
            )
        if input_data.files and not self.uses_files:
            raise AdapterInputError(
                program=self.program,
                message=(
                    f"The {self.program} adapter does not support files as additional "
                    "inputs. Remove the files from your input."
                ),
            )
